name: Post Update

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      # Tried with just pipenv but kept getting the error of "could not be found within PATH or Pipfile's [scripts]"
      - name: Install Dependencies
        run: |
          pip install pipenv
          pipenv lock -r > requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Post Update
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: |
          python post_update.py
