name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          pip install pipenv
          pipenv install
      - name: Post Update
        env:
          CONSUMER_KEY: ${{ env.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ env.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ env.ACCESS_TOKEN_SECRET }}
        run: |
          pipenv run post_update.py
